---
title: "ClavertonDown Example"
author: 'Emma Cliffe, Skills Centre: MASH, University of Bath'
date: 'August 2020'
site: bookdown::bookdown_site
lang: en
documentclass: article
classoption: a4paper
fontsize: 10pt
geometry: margin=2.5cm
output:
  clavertondown::epub_clav:
    toc: true
  clavertondown::pdf_clav:
    latex_engine: pdflatex
    dev: pdf
    keep_tex: true
    fig_caption: false
    toc: true
  clavertondown::gitbook_clav:
    split_by: section
    config:
      download: [["Notes.html", "HTML page"], ["Notes.pdf","Standard print PDF"], ["NotesClear.pdf","Clear print PDF"], ["NotesLarge.pdf","Large print PDF"], ["Notes.docx","Accessible Word document"], ["Notes.epub","Accessible EPub book" ]]
      sharing: no
  clavertondown::word_clav:
    toc: true
    number_sections: true
    keep_md: true
  clavertondown::html_clav:
    toc: true
---

\newpage
\pagenumbering{arabic}

# Introduction {-}

ClavertonDown is aimed at staff at the University of Bath which is located on Claverton Down. It uses knitr, RMarkdown and Bookdown and aims to produce a system for creating sets of lecture notes in a variety of formats, including those which are technically accessible and those which are often preferred by disabled students. We aim for the system to be usable in both pure and applied mathematical settings. Requests to adapt the system or the outputs of the system to meet these goals will be considered by MASH. The main contact email address is mash-access@bath.ac.uk but you should use the Team set up by the Centre for Learning and Teaching for support in the first instance.  

This document is **also** a work in progress. Like everything right now!

# What formats do I need to produce and why?

ClavertonDown can produce:

* HTML book
* HTML page
* Standard, clear and large print PDF
* Word document
* EPub book

From a technical point of view only three of these formats of mathematical text are accessible:

* HTML using MathJax to render all mathematical text (HTML book and page)
  * HTML formats must meet WCAG 2.1 Level AA requirements and use MathJax to render all mathematical text. 
  * You can check your document meets the legal requirement of WCAG 2.1 Level AA with e.g. [Accessibility Insights for Web plugin for Chrome](https://accessibilityinsights.io/docs/en/web/overview)
  * You can check it is MathJax by right clicking on the expression (try it in the HTML version):
  \[x = \frac{-b\pm\sqrt{b^2 - 4ac}}{2a}\]
* Word document using in-built Equation Editor for all mathematical text
  * Word formats must pass the in-built Accessibility Checker and use the in-built Equation Editor for all mathematical text.
  * You can use the in-built Word Accessibility Checker and information on [Making your Word documents accessible](https://support.office.com/en-gb/article/make-your-word-documents-accessible-to-people-with-disabilities-d9bf3683-87ac-47ea-b91a-78dcacb3c66d) to check your document.
  * You can use Review -> Read Aloud (Alt + Ctrl + Space) to check the maths 
* EPub3 using MathML for all mathematical text:
  * If the HTML format is accessible then the EPub3 output from ClavertonDown will be also

The output from ClavertonDown will meet these requirements as far as possible. However, we cannot stop you from doing things which will fail to meet requirements. In particular, if you use images, sound, videos, colour or interactive/dynamic elements within the HTML you will need to ensure that you have done so within the accessibility requirements. 

## Why do we still supply inaccessible PDFs?

It isn't possible to create accessible PDFs using LaTeX. Even if a PDF is accessible the mathematical text within it will **still be technically inaccessible** regardless of how the PDF has been produced but...

* not all accessibility is about technical access - for some a clear or large print PDF is best
* clear print is selected most often by disabled students in the Department of Mathematical Sciences.

# Testing some theorem stuff

```{theorem, label="thm1", name="Foo"}
Bookdown is needed for things like theorems and internal references
```

```{proposition, label="prp1", name="Thingy we need for \\@ref(thm:thm1)"}
You can create new theorem types
```

```{newtheorem, env="Proof", name="Of theorem \\@ref(thm:thm1)"}
Here is a proof
```

```{proof,name="Proof of theorem \\@ref(thm:thm1)"}
Here is a proof
```

```{proposition, label="prp2"}
Bookdown is needed for things like theorems and internal references
```

```{newtheorem, env='Thought', label="tho1", name="Bar"}
You can create new theorem types
```

```{newtheorem, env='Wonder'}
You can create new unumbered theorem types
```

```{newtheorem, env='Nugget', label="nug1"}
You can create new theorem types
```

Now go to \@ref(thm:thm1).

```{newtheorem, env='Solution', label="sol1"}
You can create new theorem types
```

```{solution}
Test
```